// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1181810732;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__acknowledge_matrix_update_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "acknowledge_matrix_update",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_subscription_id = <String>::sse_decode(&mut deserializer);
            let api_sequence = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>({
                            crate::api::simple::acknowledge_matrix_update(
                                api_subscription_id,
                                api_sequence,
                            )
                            .await;
                        })?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__close_matrix_updates_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_matrix_updates",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_subscription_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>({
                            crate::api::simple::close_matrix_updates(api_subscription_id).await;
                        })?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__initialize_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::SessionError>(
                    (move || async move {
                        let output_ok = crate::api::simple::initialize_session().await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__list_conversations_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_conversations",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::ConversationError>(
                    (move || async move {
                        let output_ok = crate::api::simple::list_conversations().await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__load_message_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_message_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_conversation_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::MessageHistoryError>(
                    (move || async move {
                        let output_ok =
                            crate::api::simple::load_message_history(api_conversation_id).await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_homeserver_address = <String>::sse_decode(&mut deserializer);
            let api_username = <String>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::LoginError>(
                    (move || async move {
                        let output_ok = crate::api::simple::login(
                            api_homeserver_address,
                            api_username,
                            api_password,
                        )
                        .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__logout_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "logout",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::LogoutError>(
                    (move || async move {
                        let output_ok = crate::api::simple::logout().await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__matrix_updates_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "matrix_updates",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_subscription_id = <String>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::simple::MatrixUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::MatrixStreamError>(
                    (move || async move {
                        let output_ok =
                            crate::api::simple::matrix_updates(api_subscription_id, api_sink)
                                .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__open_matrix_updates_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_matrix_updates",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::MatrixStreamError>(
                    (move || async move {
                        let output_ok = crate::api::simple::open_matrix_updates().await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__probe_server_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_server",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_address = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::ProbeError>(
                    (move || async move {
                        let output_ok = crate::api::simple::probe_server(api_address).await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__send_text_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_text_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_conversation_id = <String>::sse_decode(&mut deserializer);
            let api_body = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::simple::SendMessageError>(
                    (move || async move {
                        let output_ok =
                            crate::api::simple::send_text_message(api_conversation_id, api_body)
                                .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::simple::MatrixUpdate, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::simple::AccountSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_homeserverAddress = <String>::sse_decode(deserializer);
        return crate::api::simple::AccountSummary {
            user_id: var_userId,
            device_id: var_deviceId,
            homeserver_address: var_homeserverAddress,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::simple::ConversationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::ConversationError::NotAuthenticated,
            1 => crate::api::simple::ConversationError::Network,
            2 => crate::api::simple::ConversationError::Tls,
            3 => crate::api::simple::ConversationError::RateLimited,
            4 => crate::api::simple::ConversationError::Synchronization,
            5 => crate::api::simple::ConversationError::Internal,
            _ => unreachable!("Invalid variant for ConversationError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::ConversationSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_unreadMessageCount = <u32>::sse_decode(deserializer);
        return crate::api::simple::ConversationSummary {
            id: var_id,
            display_name: var_displayName,
            unread_message_count: var_unreadMessageCount,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::simple::ConversationSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::ConversationSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::MessageSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::MessageSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::simple::LoginError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::LoginError::InvalidServerAddress,
            1 => crate::api::simple::LoginError::InvalidInput,
            2 => crate::api::simple::LoginError::PasswordLoginUnsupported,
            3 => crate::api::simple::LoginError::InvalidCredentials,
            4 => crate::api::simple::LoginError::Network,
            5 => crate::api::simple::LoginError::Tls,
            6 => crate::api::simple::LoginError::RateLimited,
            7 => crate::api::simple::LoginError::AlreadyAuthenticated,
            8 => crate::api::simple::LoginError::LoginInProgress,
            9 => crate::api::simple::LoginError::SecureStorage,
            10 => crate::api::simple::LoginError::Persistence,
            11 => crate::api::simple::LoginError::UnusableHomeserver,
            12 => crate::api::simple::LoginError::Internal,
            _ => unreachable!("Invalid variant for LoginError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::LogoutError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::LogoutError::NotAuthenticated,
            1 => crate::api::simple::LogoutError::LogoutInProgress,
            2 => crate::api::simple::LogoutError::AuthenticationOperationInProgress,
            3 => crate::api::simple::LogoutError::SecureStorage,
            4 => crate::api::simple::LogoutError::LocalCleanup,
            5 => crate::api::simple::LogoutError::Internal,
            _ => unreachable!("Invalid variant for LogoutError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::LogoutResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_remoteStatus =
            <crate::api::simple::RemoteLogoutStatus>::sse_decode(deserializer);
        let mut var_storeCleanupPending = <bool>::sse_decode(deserializer);
        return crate::api::simple::LogoutResult {
            remote_status: var_remoteStatus,
            store_cleanup_pending: var_storeCleanupPending,
        };
    }
}

impl SseDecode for crate::api::simple::MatrixStreamError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::MatrixStreamError::NotAuthenticated,
            1 => crate::api::simple::MatrixStreamError::SubscriberLimit,
            2 => crate::api::simple::MatrixStreamError::SubscriptionClosed,
            3 => crate::api::simple::MatrixStreamError::Internal,
            _ => unreachable!("Invalid variant for MatrixStreamError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::MatrixSyncStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::MatrixSyncStatus::Connecting,
            1 => crate::api::simple::MatrixSyncStatus::Connected,
            2 => crate::api::simple::MatrixSyncStatus::Reconnecting,
            3 => crate::api::simple::MatrixSyncStatus::AuthenticationRequired,
            _ => unreachable!("Invalid variant for MatrixSyncStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::MatrixUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_subscriptionId = <String>::sse_decode(deserializer);
        let mut var_sequence = <u32>::sse_decode(deserializer);
        let mut var_kind = <crate::api::simple::MatrixUpdateKind>::sse_decode(deserializer);
        let mut var_conversationId = <Option<String>>::sse_decode(deserializer);
        let mut var_message =
            <Option<crate::api::simple::MessageSummary>>::sse_decode(deserializer);
        let mut var_status = <crate::api::simple::MatrixSyncStatus>::sse_decode(deserializer);
        return crate::api::simple::MatrixUpdate {
            subscription_id: var_subscriptionId,
            sequence: var_sequence,
            kind: var_kind,
            conversation_id: var_conversationId,
            message: var_message,
            status: var_status,
        };
    }
}

impl SseDecode for crate::api::simple::MatrixUpdateKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::MatrixUpdateKind::Message,
            1 => crate::api::simple::MatrixUpdateKind::ConversationsChanged,
            2 => crate::api::simple::MatrixUpdateKind::ResyncRequired,
            3 => crate::api::simple::MatrixUpdateKind::Status,
            _ => unreachable!("Invalid variant for MatrixUpdateKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::MessageHistoryError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::MessageHistoryError::NotAuthenticated,
            1 => crate::api::simple::MessageHistoryError::InvalidConversationId,
            2 => crate::api::simple::MessageHistoryError::ConversationNotFound,
            3 => crate::api::simple::MessageHistoryError::ConversationNotJoined,
            4 => crate::api::simple::MessageHistoryError::EncryptionUnsupported,
            5 => crate::api::simple::MessageHistoryError::Network,
            6 => crate::api::simple::MessageHistoryError::Tls,
            7 => crate::api::simple::MessageHistoryError::RateLimited,
            8 => crate::api::simple::MessageHistoryError::History,
            9 => crate::api::simple::MessageHistoryError::Internal,
            _ => unreachable!("Invalid variant for MessageHistoryError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::MessageSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_senderId = <String>::sse_decode(deserializer);
        let mut var_body = <String>::sse_decode(deserializer);
        let mut var_timestampMs = <i64>::sse_decode(deserializer);
        let mut var_isOwn = <bool>::sse_decode(deserializer);
        return crate::api::simple::MessageSummary {
            id: var_id,
            sender_id: var_senderId,
            body: var_body,
            timestamp_ms: var_timestampMs,
            is_own: var_isOwn,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::simple::AccountSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::simple::AccountSummary>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::simple::MessageSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::simple::MessageSummary>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::simple::ProbeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::ProbeError::InvalidServerAddress,
            1 => crate::api::simple::ProbeError::Network,
            2 => crate::api::simple::ProbeError::Tls,
            3 => crate::api::simple::ProbeError::UnusableHomeserver,
            4 => crate::api::simple::ProbeError::Internal,
            _ => unreachable!("Invalid variant for ProbeError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::RemoteLogoutStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::RemoteLogoutStatus::Confirmed,
            1 => crate::api::simple::RemoteLogoutStatus::AlreadyInvalid,
            2 => crate::api::simple::RemoteLogoutStatus::Network,
            3 => crate::api::simple::RemoteLogoutStatus::Tls,
            4 => crate::api::simple::RemoteLogoutStatus::RateLimited,
            5 => crate::api::simple::RemoteLogoutStatus::Server,
            6 => crate::api::simple::RemoteLogoutStatus::Internal,
            _ => unreachable!("Invalid variant for RemoteLogoutStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::SendMessageError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::SendMessageError::NotAuthenticated,
            1 => crate::api::simple::SendMessageError::InvalidConversationId,
            2 => crate::api::simple::SendMessageError::ConversationNotFound,
            3 => crate::api::simple::SendMessageError::ConversationNotJoined,
            4 => crate::api::simple::SendMessageError::EncryptionUnsupported,
            5 => crate::api::simple::SendMessageError::EmptyMessage,
            6 => crate::api::simple::SendMessageError::MessageTooLong,
            7 => crate::api::simple::SendMessageError::SendInProgress,
            8 => crate::api::simple::SendMessageError::Network,
            9 => crate::api::simple::SendMessageError::Tls,
            10 => crate::api::simple::SendMessageError::RateLimited,
            11 => crate::api::simple::SendMessageError::Send,
            12 => crate::api::simple::SendMessageError::Internal,
            _ => unreachable!("Invalid variant for SendMessageError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::SendMessageResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <String>::sse_decode(deserializer);
        return crate::api::simple::SendMessageResult {
            event_id: var_eventId,
        };
    }
}

impl SseDecode for crate::api::simple::ServerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_serverAddress = <String>::sse_decode(deserializer);
        let mut var_supportsPasswordLogin = <bool>::sse_decode(deserializer);
        return crate::api::simple::ServerInfo {
            server_address: var_serverAddress,
            supports_password_login: var_supportsPasswordLogin,
        };
    }
}

impl SseDecode for crate::api::simple::SessionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::SessionError::OperationInProgress,
            1 => crate::api::simple::SessionError::Network,
            2 => crate::api::simple::SessionError::Tls,
            3 => crate::api::simple::SessionError::InvalidSession,
            4 => crate::api::simple::SessionError::CorruptedSession,
            5 => crate::api::simple::SessionError::SecureStorage,
            6 => crate::api::simple::SessionError::Persistence,
            7 => crate::api::simple::SessionError::Internal,
            _ => unreachable!("Invalid variant for SessionError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::SessionState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_account =
            <Option<crate::api::simple::AccountSummary>>::sse_decode(deserializer);
        return crate::api::simple::SessionState {
            account: var_account,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__acknowledge_matrix_update_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__simple__close_matrix_updates_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__simple__initialize_session_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__simple__list_conversations_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__simple__load_message_history_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__simple__login_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__simple__logout_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__simple__matrix_updates_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__simple__open_matrix_updates_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__simple__probe_server_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__simple__send_text_message_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::AccountSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.user_id.into_into_dart().into_dart(),
            self.device_id.into_into_dart().into_dart(),
            self.homeserver_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::AccountSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::AccountSummary>
    for crate::api::simple::AccountSummary
{
    fn into_into_dart(self) -> crate::api::simple::AccountSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ConversationError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotAuthenticated => 0.into_dart(),
            Self::Network => 1.into_dart(),
            Self::Tls => 2.into_dart(),
            Self::RateLimited => 3.into_dart(),
            Self::Synchronization => 4.into_dart(),
            Self::Internal => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ConversationError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ConversationError>
    for crate::api::simple::ConversationError
{
    fn into_into_dart(self) -> crate::api::simple::ConversationError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ConversationSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.unread_message_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ConversationSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ConversationSummary>
    for crate::api::simple::ConversationSummary
{
    fn into_into_dart(self) -> crate::api::simple::ConversationSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::LoginError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidServerAddress => 0.into_dart(),
            Self::InvalidInput => 1.into_dart(),
            Self::PasswordLoginUnsupported => 2.into_dart(),
            Self::InvalidCredentials => 3.into_dart(),
            Self::Network => 4.into_dart(),
            Self::Tls => 5.into_dart(),
            Self::RateLimited => 6.into_dart(),
            Self::AlreadyAuthenticated => 7.into_dart(),
            Self::LoginInProgress => 8.into_dart(),
            Self::SecureStorage => 9.into_dart(),
            Self::Persistence => 10.into_dart(),
            Self::UnusableHomeserver => 11.into_dart(),
            Self::Internal => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::LoginError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::LoginError>
    for crate::api::simple::LoginError
{
    fn into_into_dart(self) -> crate::api::simple::LoginError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::LogoutError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotAuthenticated => 0.into_dart(),
            Self::LogoutInProgress => 1.into_dart(),
            Self::AuthenticationOperationInProgress => 2.into_dart(),
            Self::SecureStorage => 3.into_dart(),
            Self::LocalCleanup => 4.into_dart(),
            Self::Internal => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::LogoutError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::LogoutError>
    for crate::api::simple::LogoutError
{
    fn into_into_dart(self) -> crate::api::simple::LogoutError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::LogoutResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.remote_status.into_into_dart().into_dart(),
            self.store_cleanup_pending.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::LogoutResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::LogoutResult>
    for crate::api::simple::LogoutResult
{
    fn into_into_dart(self) -> crate::api::simple::LogoutResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MatrixStreamError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotAuthenticated => 0.into_dart(),
            Self::SubscriberLimit => 1.into_dart(),
            Self::SubscriptionClosed => 2.into_dart(),
            Self::Internal => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MatrixStreamError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MatrixStreamError>
    for crate::api::simple::MatrixStreamError
{
    fn into_into_dart(self) -> crate::api::simple::MatrixStreamError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MatrixSyncStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Connecting => 0.into_dart(),
            Self::Connected => 1.into_dart(),
            Self::Reconnecting => 2.into_dart(),
            Self::AuthenticationRequired => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MatrixSyncStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MatrixSyncStatus>
    for crate::api::simple::MatrixSyncStatus
{
    fn into_into_dart(self) -> crate::api::simple::MatrixSyncStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MatrixUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.subscription_id.into_into_dart().into_dart(),
            self.sequence.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.conversation_id.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MatrixUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MatrixUpdate>
    for crate::api::simple::MatrixUpdate
{
    fn into_into_dart(self) -> crate::api::simple::MatrixUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MatrixUpdateKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Message => 0.into_dart(),
            Self::ConversationsChanged => 1.into_dart(),
            Self::ResyncRequired => 2.into_dart(),
            Self::Status => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MatrixUpdateKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MatrixUpdateKind>
    for crate::api::simple::MatrixUpdateKind
{
    fn into_into_dart(self) -> crate::api::simple::MatrixUpdateKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MessageHistoryError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotAuthenticated => 0.into_dart(),
            Self::InvalidConversationId => 1.into_dart(),
            Self::ConversationNotFound => 2.into_dart(),
            Self::ConversationNotJoined => 3.into_dart(),
            Self::EncryptionUnsupported => 4.into_dart(),
            Self::Network => 5.into_dart(),
            Self::Tls => 6.into_dart(),
            Self::RateLimited => 7.into_dart(),
            Self::History => 8.into_dart(),
            Self::Internal => 9.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MessageHistoryError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MessageHistoryError>
    for crate::api::simple::MessageHistoryError
{
    fn into_into_dart(self) -> crate::api::simple::MessageHistoryError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MessageSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.sender_id.into_into_dart().into_dart(),
            self.body.into_into_dart().into_dart(),
            self.timestamp_ms.into_into_dart().into_dart(),
            self.is_own.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MessageSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MessageSummary>
    for crate::api::simple::MessageSummary
{
    fn into_into_dart(self) -> crate::api::simple::MessageSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ProbeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidServerAddress => 0.into_dart(),
            Self::Network => 1.into_dart(),
            Self::Tls => 2.into_dart(),
            Self::UnusableHomeserver => 3.into_dart(),
            Self::Internal => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ProbeError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ProbeError>
    for crate::api::simple::ProbeError
{
    fn into_into_dart(self) -> crate::api::simple::ProbeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::RemoteLogoutStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Confirmed => 0.into_dart(),
            Self::AlreadyInvalid => 1.into_dart(),
            Self::Network => 2.into_dart(),
            Self::Tls => 3.into_dart(),
            Self::RateLimited => 4.into_dart(),
            Self::Server => 5.into_dart(),
            Self::Internal => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::RemoteLogoutStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::RemoteLogoutStatus>
    for crate::api::simple::RemoteLogoutStatus
{
    fn into_into_dart(self) -> crate::api::simple::RemoteLogoutStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::SendMessageError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotAuthenticated => 0.into_dart(),
            Self::InvalidConversationId => 1.into_dart(),
            Self::ConversationNotFound => 2.into_dart(),
            Self::ConversationNotJoined => 3.into_dart(),
            Self::EncryptionUnsupported => 4.into_dart(),
            Self::EmptyMessage => 5.into_dart(),
            Self::MessageTooLong => 6.into_dart(),
            Self::SendInProgress => 7.into_dart(),
            Self::Network => 8.into_dart(),
            Self::Tls => 9.into_dart(),
            Self::RateLimited => 10.into_dart(),
            Self::Send => 11.into_dart(),
            Self::Internal => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::SendMessageError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::SendMessageError>
    for crate::api::simple::SendMessageError
{
    fn into_into_dart(self) -> crate::api::simple::SendMessageError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::SendMessageResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.event_id.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::SendMessageResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::SendMessageResult>
    for crate::api::simple::SendMessageResult
{
    fn into_into_dart(self) -> crate::api::simple::SendMessageResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ServerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.server_address.into_into_dart().into_dart(),
            self.supports_password_login.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ServerInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ServerInfo>
    for crate::api::simple::ServerInfo
{
    fn into_into_dart(self) -> crate::api::simple::ServerInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::SessionError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::OperationInProgress => 0.into_dart(),
            Self::Network => 1.into_dart(),
            Self::Tls => 2.into_dart(),
            Self::InvalidSession => 3.into_dart(),
            Self::CorruptedSession => 4.into_dart(),
            Self::SecureStorage => 5.into_dart(),
            Self::Persistence => 6.into_dart(),
            Self::Internal => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::SessionError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::SessionError>
    for crate::api::simple::SessionError
{
    fn into_into_dart(self) -> crate::api::simple::SessionError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::SessionState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.account.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::SessionState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::SessionState>
    for crate::api::simple::SessionState
{
    fn into_into_dart(self) -> crate::api::simple::SessionState {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::simple::MatrixUpdate, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::simple::AccountSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.user_id, serializer);
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.homeserver_address, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::simple::ConversationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::ConversationError::NotAuthenticated => 0,
                crate::api::simple::ConversationError::Network => 1,
                crate::api::simple::ConversationError::Tls => 2,
                crate::api::simple::ConversationError::RateLimited => 3,
                crate::api::simple::ConversationError::Synchronization => 4,
                crate::api::simple::ConversationError::Internal => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::ConversationSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <u32>::sse_encode(self.unread_message_count, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::simple::ConversationSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::ConversationSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::MessageSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::MessageSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::simple::LoginError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::LoginError::InvalidServerAddress => 0,
                crate::api::simple::LoginError::InvalidInput => 1,
                crate::api::simple::LoginError::PasswordLoginUnsupported => 2,
                crate::api::simple::LoginError::InvalidCredentials => 3,
                crate::api::simple::LoginError::Network => 4,
                crate::api::simple::LoginError::Tls => 5,
                crate::api::simple::LoginError::RateLimited => 6,
                crate::api::simple::LoginError::AlreadyAuthenticated => 7,
                crate::api::simple::LoginError::LoginInProgress => 8,
                crate::api::simple::LoginError::SecureStorage => 9,
                crate::api::simple::LoginError::Persistence => 10,
                crate::api::simple::LoginError::UnusableHomeserver => 11,
                crate::api::simple::LoginError::Internal => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::LogoutError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::LogoutError::NotAuthenticated => 0,
                crate::api::simple::LogoutError::LogoutInProgress => 1,
                crate::api::simple::LogoutError::AuthenticationOperationInProgress => 2,
                crate::api::simple::LogoutError::SecureStorage => 3,
                crate::api::simple::LogoutError::LocalCleanup => 4,
                crate::api::simple::LogoutError::Internal => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::LogoutResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::simple::RemoteLogoutStatus>::sse_encode(self.remote_status, serializer);
        <bool>::sse_encode(self.store_cleanup_pending, serializer);
    }
}

impl SseEncode for crate::api::simple::MatrixStreamError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::MatrixStreamError::NotAuthenticated => 0,
                crate::api::simple::MatrixStreamError::SubscriberLimit => 1,
                crate::api::simple::MatrixStreamError::SubscriptionClosed => 2,
                crate::api::simple::MatrixStreamError::Internal => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::MatrixSyncStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::MatrixSyncStatus::Connecting => 0,
                crate::api::simple::MatrixSyncStatus::Connected => 1,
                crate::api::simple::MatrixSyncStatus::Reconnecting => 2,
                crate::api::simple::MatrixSyncStatus::AuthenticationRequired => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::MatrixUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.subscription_id, serializer);
        <u32>::sse_encode(self.sequence, serializer);
        <crate::api::simple::MatrixUpdateKind>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.conversation_id, serializer);
        <Option<crate::api::simple::MessageSummary>>::sse_encode(self.message, serializer);
        <crate::api::simple::MatrixSyncStatus>::sse_encode(self.status, serializer);
    }
}

impl SseEncode for crate::api::simple::MatrixUpdateKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::MatrixUpdateKind::Message => 0,
                crate::api::simple::MatrixUpdateKind::ConversationsChanged => 1,
                crate::api::simple::MatrixUpdateKind::ResyncRequired => 2,
                crate::api::simple::MatrixUpdateKind::Status => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::MessageHistoryError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::MessageHistoryError::NotAuthenticated => 0,
                crate::api::simple::MessageHistoryError::InvalidConversationId => 1,
                crate::api::simple::MessageHistoryError::ConversationNotFound => 2,
                crate::api::simple::MessageHistoryError::ConversationNotJoined => 3,
                crate::api::simple::MessageHistoryError::EncryptionUnsupported => 4,
                crate::api::simple::MessageHistoryError::Network => 5,
                crate::api::simple::MessageHistoryError::Tls => 6,
                crate::api::simple::MessageHistoryError::RateLimited => 7,
                crate::api::simple::MessageHistoryError::History => 8,
                crate::api::simple::MessageHistoryError::Internal => 9,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::MessageSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.sender_id, serializer);
        <String>::sse_encode(self.body, serializer);
        <i64>::sse_encode(self.timestamp_ms, serializer);
        <bool>::sse_encode(self.is_own, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::simple::AccountSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::simple::AccountSummary>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::simple::MessageSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::simple::MessageSummary>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::simple::ProbeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::ProbeError::InvalidServerAddress => 0,
                crate::api::simple::ProbeError::Network => 1,
                crate::api::simple::ProbeError::Tls => 2,
                crate::api::simple::ProbeError::UnusableHomeserver => 3,
                crate::api::simple::ProbeError::Internal => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::RemoteLogoutStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::RemoteLogoutStatus::Confirmed => 0,
                crate::api::simple::RemoteLogoutStatus::AlreadyInvalid => 1,
                crate::api::simple::RemoteLogoutStatus::Network => 2,
                crate::api::simple::RemoteLogoutStatus::Tls => 3,
                crate::api::simple::RemoteLogoutStatus::RateLimited => 4,
                crate::api::simple::RemoteLogoutStatus::Server => 5,
                crate::api::simple::RemoteLogoutStatus::Internal => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::SendMessageError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::SendMessageError::NotAuthenticated => 0,
                crate::api::simple::SendMessageError::InvalidConversationId => 1,
                crate::api::simple::SendMessageError::ConversationNotFound => 2,
                crate::api::simple::SendMessageError::ConversationNotJoined => 3,
                crate::api::simple::SendMessageError::EncryptionUnsupported => 4,
                crate::api::simple::SendMessageError::EmptyMessage => 5,
                crate::api::simple::SendMessageError::MessageTooLong => 6,
                crate::api::simple::SendMessageError::SendInProgress => 7,
                crate::api::simple::SendMessageError::Network => 8,
                crate::api::simple::SendMessageError::Tls => 9,
                crate::api::simple::SendMessageError::RateLimited => 10,
                crate::api::simple::SendMessageError::Send => 11,
                crate::api::simple::SendMessageError::Internal => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::SendMessageResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.event_id, serializer);
    }
}

impl SseEncode for crate::api::simple::ServerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.server_address, serializer);
        <bool>::sse_encode(self.supports_password_login, serializer);
    }
}

impl SseEncode for crate::api::simple::SessionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::SessionError::OperationInProgress => 0,
                crate::api::simple::SessionError::Network => 1,
                crate::api::simple::SessionError::Tls => 2,
                crate::api::simple::SessionError::InvalidSession => 3,
                crate::api::simple::SessionError::CorruptedSession => 4,
                crate::api::simple::SessionError::SecureStorage => 5,
                crate::api::simple::SessionError::Persistence => 6,
                crate::api::simple::SessionError::Internal => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::SessionState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::simple::AccountSummary>>::sse_encode(self.account, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
