// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountSummary dco_decode_account_summary(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountSummary dco_decode_box_autoadd_account_summary(dynamic raw);

  @protected
  ConversationError dco_decode_conversation_error(dynamic raw);

  @protected
  ConversationSummary dco_decode_conversation_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<ConversationSummary> dco_decode_list_conversation_summary(dynamic raw);

  @protected
  List<MessageSummary> dco_decode_list_message_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LoginError dco_decode_login_error(dynamic raw);

  @protected
  LogoutError dco_decode_logout_error(dynamic raw);

  @protected
  LogoutResult dco_decode_logout_result(dynamic raw);

  @protected
  MessageHistoryError dco_decode_message_history_error(dynamic raw);

  @protected
  MessageSummary dco_decode_message_summary(dynamic raw);

  @protected
  AccountSummary? dco_decode_opt_box_autoadd_account_summary(dynamic raw);

  @protected
  ProbeError dco_decode_probe_error(dynamic raw);

  @protected
  RemoteLogoutStatus dco_decode_remote_logout_status(dynamic raw);

  @protected
  SendMessageError dco_decode_send_message_error(dynamic raw);

  @protected
  SendMessageResult dco_decode_send_message_result(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  SessionError dco_decode_session_error(dynamic raw);

  @protected
  SessionState dco_decode_session_state(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountSummary sse_decode_account_summary(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountSummary sse_decode_box_autoadd_account_summary(
    SseDeserializer deserializer,
  );

  @protected
  ConversationError sse_decode_conversation_error(SseDeserializer deserializer);

  @protected
  ConversationSummary sse_decode_conversation_summary(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<ConversationSummary> sse_decode_list_conversation_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageSummary> sse_decode_list_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LoginError sse_decode_login_error(SseDeserializer deserializer);

  @protected
  LogoutError sse_decode_logout_error(SseDeserializer deserializer);

  @protected
  LogoutResult sse_decode_logout_result(SseDeserializer deserializer);

  @protected
  MessageHistoryError sse_decode_message_history_error(
    SseDeserializer deserializer,
  );

  @protected
  MessageSummary sse_decode_message_summary(SseDeserializer deserializer);

  @protected
  AccountSummary? sse_decode_opt_box_autoadd_account_summary(
    SseDeserializer deserializer,
  );

  @protected
  ProbeError sse_decode_probe_error(SseDeserializer deserializer);

  @protected
  RemoteLogoutStatus sse_decode_remote_logout_status(
    SseDeserializer deserializer,
  );

  @protected
  SendMessageError sse_decode_send_message_error(SseDeserializer deserializer);

  @protected
  SendMessageResult sse_decode_send_message_result(
    SseDeserializer deserializer,
  );

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  SessionError sse_decode_session_error(SseDeserializer deserializer);

  @protected
  SessionState sse_decode_session_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_summary(
    AccountSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_summary(
    AccountSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_error(
    ConversationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_summary(
    ConversationSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation_summary(
    List<ConversationSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_summary(
    List<MessageSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_error(LoginError self, SseSerializer serializer);

  @protected
  void sse_encode_logout_error(LogoutError self, SseSerializer serializer);

  @protected
  void sse_encode_logout_result(LogoutResult self, SseSerializer serializer);

  @protected
  void sse_encode_message_history_error(
    MessageHistoryError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_summary(
    MessageSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_account_summary(
    AccountSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_probe_error(ProbeError self, SseSerializer serializer);

  @protected
  void sse_encode_remote_logout_status(
    RemoteLogoutStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_message_error(
    SendMessageError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_message_result(
    SendMessageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_session_error(SessionError self, SseSerializer serializer);

  @protected
  void sse_encode_session_state(SessionState self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
