// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1181810732;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_desktop_chat_client',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleAcknowledgeMatrixUpdate({
    required String subscriptionId,
    required int sequence,
  });

  Future<void> crateApiSimpleCloseMatrixUpdates({
    required String subscriptionId,
  });

  Future<SessionState> crateApiSimpleInitializeSession();

  Future<List<ConversationSummary>> crateApiSimpleListConversations();

  Future<List<MessageSummary>> crateApiSimpleLoadMessageHistory({
    required String conversationId,
  });

  Future<AccountSummary> crateApiSimpleLogin({
    required String homeserverAddress,
    required String username,
    required String password,
  });

  Future<LogoutResult> crateApiSimpleLogout();

  Stream<MatrixUpdate> crateApiSimpleMatrixUpdates({
    required String subscriptionId,
  });

  Future<String> crateApiSimpleOpenMatrixUpdates();

  Future<ServerInfo> crateApiSimpleProbeServer({required String address});

  Future<SendMessageResult> crateApiSimpleSendTextMessage({
    required String conversationId,
    required String body,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleAcknowledgeMatrixUpdate({
    required String subscriptionId,
    required int sequence,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(subscriptionId, serializer);
          sse_encode_u_32(sequence, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAcknowledgeMatrixUpdateConstMeta,
        argValues: [subscriptionId, sequence],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAcknowledgeMatrixUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "acknowledge_matrix_update",
        argNames: ["subscriptionId", "sequence"],
      );

  @override
  Future<void> crateApiSimpleCloseMatrixUpdates({
    required String subscriptionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(subscriptionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCloseMatrixUpdatesConstMeta,
        argValues: [subscriptionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCloseMatrixUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "close_matrix_updates",
        argNames: ["subscriptionId"],
      );

  @override
  Future<SessionState> crateApiSimpleInitializeSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_state,
          decodeErrorData: sse_decode_session_error,
        ),
        constMeta: kCrateApiSimpleInitializeSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitializeSessionConstMeta =>
      const TaskConstMeta(debugName: "initialize_session", argNames: []);

  @override
  Future<List<ConversationSummary>> crateApiSimpleListConversations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_summary,
          decodeErrorData: sse_decode_conversation_error,
        ),
        constMeta: kCrateApiSimpleListConversationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListConversationsConstMeta =>
      const TaskConstMeta(debugName: "list_conversations", argNames: []);

  @override
  Future<List<MessageSummary>> crateApiSimpleLoadMessageHistory({
    required String conversationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(conversationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_summary,
          decodeErrorData: sse_decode_message_history_error,
        ),
        constMeta: kCrateApiSimpleLoadMessageHistoryConstMeta,
        argValues: [conversationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLoadMessageHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "load_message_history",
        argNames: ["conversationId"],
      );

  @override
  Future<AccountSummary> crateApiSimpleLogin({
    required String homeserverAddress,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserverAddress, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_summary,
          decodeErrorData: sse_decode_login_error,
        ),
        constMeta: kCrateApiSimpleLoginConstMeta,
        argValues: [homeserverAddress, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLoginConstMeta => const TaskConstMeta(
    debugName: "login",
    argNames: ["homeserverAddress", "username", "password"],
  );

  @override
  Future<LogoutResult> crateApiSimpleLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_logout_result,
          decodeErrorData: sse_decode_logout_error,
        ),
        constMeta: kCrateApiSimpleLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Stream<MatrixUpdate> crateApiSimpleMatrixUpdates({
    required String subscriptionId,
  }) {
    final sink = RustStreamSink<MatrixUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(subscriptionId, serializer);
            sse_encode_StreamSink_matrix_update_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_matrix_stream_error,
          ),
          constMeta: kCrateApiSimpleMatrixUpdatesConstMeta,
          argValues: [subscriptionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMatrixUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "matrix_updates",
        argNames: ["subscriptionId", "sink"],
      );

  @override
  Future<String> crateApiSimpleOpenMatrixUpdates() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_matrix_stream_error,
        ),
        constMeta: kCrateApiSimpleOpenMatrixUpdatesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOpenMatrixUpdatesConstMeta =>
      const TaskConstMeta(debugName: "open_matrix_updates", argNames: []);

  @override
  Future<ServerInfo> crateApiSimpleProbeServer({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_info,
          decodeErrorData: sse_decode_probe_error,
        ),
        constMeta: kCrateApiSimpleProbeServerConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProbeServerConstMeta =>
      const TaskConstMeta(debugName: "probe_server", argNames: ["address"]);

  @override
  Future<SendMessageResult> crateApiSimpleSendTextMessage({
    required String conversationId,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(conversationId, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_message_result,
          decodeErrorData: sse_decode_send_message_error,
        ),
        constMeta: kCrateApiSimpleSendTextMessageConstMeta,
        argValues: [conversationId, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSendTextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_text_message",
        argNames: ["conversationId", "body"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<MatrixUpdate> dco_decode_StreamSink_matrix_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountSummary dco_decode_account_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AccountSummary(
      userId: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      homeserverAddress: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountSummary dco_decode_box_autoadd_account_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_summary(raw);
  }

  @protected
  MessageSummary dco_decode_box_autoadd_message_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message_summary(raw);
  }

  @protected
  ConversationError dco_decode_conversation_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConversationError.values[raw as int];
  }

  @protected
  ConversationSummary dco_decode_conversation_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConversationSummary(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      unreadMessageCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ConversationSummary> dco_decode_list_conversation_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation_summary).toList();
  }

  @protected
  List<MessageSummary> dco_decode_list_message_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LoginError dco_decode_login_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginError.values[raw as int];
  }

  @protected
  LogoutError dco_decode_logout_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LogoutError.values[raw as int];
  }

  @protected
  LogoutResult dco_decode_logout_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LogoutResult(
      remoteStatus: dco_decode_remote_logout_status(arr[0]),
      storeCleanupPending: dco_decode_bool(arr[1]),
    );
  }

  @protected
  MatrixStreamError dco_decode_matrix_stream_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixStreamError.values[raw as int];
  }

  @protected
  MatrixSyncStatus dco_decode_matrix_sync_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixSyncStatus.values[raw as int];
  }

  @protected
  MatrixUpdate dco_decode_matrix_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MatrixUpdate(
      subscriptionId: dco_decode_String(arr[0]),
      sequence: dco_decode_u_32(arr[1]),
      kind: dco_decode_matrix_update_kind(arr[2]),
      conversationId: dco_decode_opt_String(arr[3]),
      message: dco_decode_opt_box_autoadd_message_summary(arr[4]),
      status: dco_decode_matrix_sync_status(arr[5]),
    );
  }

  @protected
  MatrixUpdateKind dco_decode_matrix_update_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixUpdateKind.values[raw as int];
  }

  @protected
  MessageHistoryError dco_decode_message_history_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageHistoryError.values[raw as int];
  }

  @protected
  MessageSummary dco_decode_message_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MessageSummary(
      id: dco_decode_String(arr[0]),
      senderId: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      timestampMs: dco_decode_i_64(arr[3]),
      isOwn: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccountSummary? dco_decode_opt_box_autoadd_account_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_account_summary(raw);
  }

  @protected
  MessageSummary? dco_decode_opt_box_autoadd_message_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_message_summary(raw);
  }

  @protected
  ProbeError dco_decode_probe_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProbeError.values[raw as int];
  }

  @protected
  RemoteLogoutStatus dco_decode_remote_logout_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RemoteLogoutStatus.values[raw as int];
  }

  @protected
  SendMessageError dco_decode_send_message_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendMessageError.values[raw as int];
  }

  @protected
  SendMessageResult dco_decode_send_message_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SendMessageResult(eventId: dco_decode_String(arr[0]));
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ServerInfo(
      serverAddress: dco_decode_String(arr[0]),
      supportsPasswordLogin: dco_decode_bool(arr[1]),
    );
  }

  @protected
  SessionError dco_decode_session_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionError.values[raw as int];
  }

  @protected
  SessionState dco_decode_session_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SessionState(
      account: dco_decode_opt_box_autoadd_account_summary(arr[0]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<MatrixUpdate> sse_decode_StreamSink_matrix_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountSummary sse_decode_account_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_homeserverAddress = sse_decode_String(deserializer);
    return AccountSummary(
      userId: var_userId,
      deviceId: var_deviceId,
      homeserverAddress: var_homeserverAddress,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountSummary sse_decode_box_autoadd_account_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_summary(deserializer));
  }

  @protected
  MessageSummary sse_decode_box_autoadd_message_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message_summary(deserializer));
  }

  @protected
  ConversationError sse_decode_conversation_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConversationError.values[inner];
  }

  @protected
  ConversationSummary sse_decode_conversation_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_unreadMessageCount = sse_decode_u_32(deserializer);
    return ConversationSummary(
      id: var_id,
      displayName: var_displayName,
      unreadMessageCount: var_unreadMessageCount,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ConversationSummary> sse_decode_list_conversation_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageSummary> sse_decode_list_message_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LoginError sse_decode_login_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LoginError.values[inner];
  }

  @protected
  LogoutError sse_decode_logout_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LogoutError.values[inner];
  }

  @protected
  LogoutResult sse_decode_logout_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_remoteStatus = sse_decode_remote_logout_status(deserializer);
    var var_storeCleanupPending = sse_decode_bool(deserializer);
    return LogoutResult(
      remoteStatus: var_remoteStatus,
      storeCleanupPending: var_storeCleanupPending,
    );
  }

  @protected
  MatrixStreamError sse_decode_matrix_stream_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatrixStreamError.values[inner];
  }

  @protected
  MatrixSyncStatus sse_decode_matrix_sync_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatrixSyncStatus.values[inner];
  }

  @protected
  MatrixUpdate sse_decode_matrix_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subscriptionId = sse_decode_String(deserializer);
    var var_sequence = sse_decode_u_32(deserializer);
    var var_kind = sse_decode_matrix_update_kind(deserializer);
    var var_conversationId = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_opt_box_autoadd_message_summary(deserializer);
    var var_status = sse_decode_matrix_sync_status(deserializer);
    return MatrixUpdate(
      subscriptionId: var_subscriptionId,
      sequence: var_sequence,
      kind: var_kind,
      conversationId: var_conversationId,
      message: var_message,
      status: var_status,
    );
  }

  @protected
  MatrixUpdateKind sse_decode_matrix_update_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatrixUpdateKind.values[inner];
  }

  @protected
  MessageHistoryError sse_decode_message_history_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageHistoryError.values[inner];
  }

  @protected
  MessageSummary sse_decode_message_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_isOwn = sse_decode_bool(deserializer);
    return MessageSummary(
      id: var_id,
      senderId: var_senderId,
      body: var_body,
      timestampMs: var_timestampMs,
      isOwn: var_isOwn,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccountSummary? sse_decode_opt_box_autoadd_account_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_account_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MessageSummary? sse_decode_opt_box_autoadd_message_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_message_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProbeError sse_decode_probe_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProbeError.values[inner];
  }

  @protected
  RemoteLogoutStatus sse_decode_remote_logout_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RemoteLogoutStatus.values[inner];
  }

  @protected
  SendMessageError sse_decode_send_message_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SendMessageError.values[inner];
  }

  @protected
  SendMessageResult sse_decode_send_message_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    return SendMessageResult(eventId: var_eventId);
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverAddress = sse_decode_String(deserializer);
    var var_supportsPasswordLogin = sse_decode_bool(deserializer);
    return ServerInfo(
      serverAddress: var_serverAddress,
      supportsPasswordLogin: var_supportsPasswordLogin,
    );
  }

  @protected
  SessionError sse_decode_session_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionError.values[inner];
  }

  @protected
  SessionState sse_decode_session_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_opt_box_autoadd_account_summary(deserializer);
    return SessionState(account: var_account);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_matrix_update_Sse(
    RustStreamSink<MatrixUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_summary(
    AccountSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.homeserverAddress, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account_summary(
    AccountSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_summary(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_message_summary(
    MessageSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message_summary(self, serializer);
  }

  @protected
  void sse_encode_conversation_error(
    ConversationError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_conversation_summary(
    ConversationSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_u_32(self.unreadMessageCount, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_conversation_summary(
    List<ConversationSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_summary(
    List<MessageSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_login_error(LoginError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_logout_error(LogoutError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_logout_result(LogoutResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_remote_logout_status(self.remoteStatus, serializer);
    sse_encode_bool(self.storeCleanupPending, serializer);
  }

  @protected
  void sse_encode_matrix_stream_error(
    MatrixStreamError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_matrix_sync_status(
    MatrixSyncStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_matrix_update(MatrixUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subscriptionId, serializer);
    sse_encode_u_32(self.sequence, serializer);
    sse_encode_matrix_update_kind(self.kind, serializer);
    sse_encode_opt_String(self.conversationId, serializer);
    sse_encode_opt_box_autoadd_message_summary(self.message, serializer);
    sse_encode_matrix_sync_status(self.status, serializer);
  }

  @protected
  void sse_encode_matrix_update_kind(
    MatrixUpdateKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_message_history_error(
    MessageHistoryError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_message_summary(
    MessageSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_bool(self.isOwn, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_account_summary(
    AccountSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_account_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_message_summary(
    MessageSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_message_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_probe_error(ProbeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_remote_logout_status(
    RemoteLogoutStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_send_message_error(
    SendMessageError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_send_message_result(
    SendMessageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverAddress, serializer);
    sse_encode_bool(self.supportsPasswordLogin, serializer);
  }

  @protected
  void sse_encode_session_error(SessionError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_state(SessionState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_account_summary(self.account, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
