// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Consulta os métodos de acesso sem autenticar ou reter um cliente global.
Future<ServerInfo> probeServer({required String address}) =>
    RustLib.instance.api.crateApiSimpleProbeServer(address: address);

/// A senha atravessa a ponte somente nesta direção e não integra o estado da conta.
Future<AccountSummary> login({
  required String homeserverAddress,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSimpleLogin(
  homeserverAddress: homeserverAddress,
  username: username,
  password: password,
);

/// Lê o retrato do store atualizado pelo único proprietário de sync contínuo.
Future<List<ConversationSummary>> listConversations() =>
    RustLib.instance.api.crateApiSimpleListConversations();

/// Aceita somente um convite conhecido; o SDK mantém sessão e associação em Rust.
Future<ConversationSummary> acceptRoomInvitation({
  required String conversationId,
}) => RustLib.instance.api.crateApiSimpleAcceptRoomInvitation(
  conversationId: conversationId,
);

/// Marca a sala como lida com recibo privado, sem divulgar a leitura a outros usuários.
Future<void> markConversationRead({required String conversationId}) => RustLib
    .instance
    .api
    .crateApiSimpleMarkConversationRead(conversationId: conversationId);

/// Consulta primeiro a autoridade em memória, inclusive após hot restart do Dart.
Future<SessionState> initializeSession() =>
    RustLib.instance.api.crateApiSimpleInitializeSession();

/// Encerra a sessão remota quando possível e remove a capacidade local de restauração.
Future<LogoutResult> logout() => RustLib.instance.api.crateApiSimpleLogout();

/// Retorna um retrato limitado do histórico textual, do mais antigo ao mais novo.
Future<List<MessageSummary>> loadMessageHistory({
  required String conversationId,
}) => RustLib.instance.api.crateApiSimpleLoadMessageHistory(
  conversationId: conversationId,
);

/// Envia texto literal; a tarefa nativa finita sobrevive ao cancelamento do await.
Future<SendMessageResult> sendTextMessage({
  required String conversationId,
  required String body,
}) => RustLib.instance.api.crateApiSimpleSendTextMessage(
  conversationId: conversationId,
  body: body,
);

/// Registra um consumidor no broadcast limitado da sessão atual, sem iniciar sync.
Future<String> openMatrixUpdates() =>
    RustLib.instance.api.crateApiSimpleOpenMatrixUpdates();

/// StreamSink gera `Stream<MatrixUpdate>` em Dart. Um evento em voo por consumidor.
Stream<MatrixUpdate> matrixUpdates({required String subscriptionId}) => RustLib
    .instance
    .api
    .crateApiSimpleMatrixUpdates(subscriptionId: subscriptionId);

/// ACK de consumo limita inclusive a fila da porta FRB; não consulta atualizações.
Future<void> acknowledgeMatrixUpdate({
  required String subscriptionId,
  required int sequence,
}) => RustLib.instance.api.crateApiSimpleAcknowledgeMatrixUpdate(
  subscriptionId: subscriptionId,
  sequence: sequence,
);

Future<void> closeMatrixUpdates({required String subscriptionId}) => RustLib
    .instance
    .api
    .crateApiSimpleCloseMatrixUpdates(subscriptionId: subscriptionId);

/// Projeção pública da conta; a sessão e seus segredos permanecem no SDK em Rust.
class AccountSummary {
  final String userId;
  final String deviceId;
  final String homeserverAddress;

  const AccountSummary({
    required this.userId,
    required this.deviceId,
    required this.homeserverAddress,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ deviceId.hashCode ^ homeserverAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountSummary &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserverAddress == other.homeserverAddress;
}

/// Categorias seguras, sem respostas do servidor nem segredos da sessão.
enum ConversationError {
  notAuthenticated,
  network,
  tls,
  rateLimited,
  synchronization,
  internal,
}

/// Resumo de apresentação; o identificador é opaco para Flutter, sem tipos Matrix.
class ConversationSummary {
  final String id;
  final String displayName;
  final int unreadMessageCount;
  final bool isEncrypted;
  final bool isInvited;

  const ConversationSummary({
    required this.id,
    required this.displayName,
    this.unreadMessageCount = 0,
    this.isEncrypted = false,
    this.isInvited = false,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      unreadMessageCount.hashCode ^
      isEncrypted.hashCode ^
      isInvited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          unreadMessageCount == other.unreadMessageCount &&
          isEncrypted == other.isEncrypted &&
          isInvited == other.isInvited;
}

/// Falhas estáveis sem mensagens, respostas ou objetos de autenticação do SDK.
enum LoginError {
  invalidServerAddress,
  invalidInput,
  passwordLoginUnsupported,
  invalidCredentials,
  network,
  tls,
  rateLimited,
  alreadyAuthenticated,
  loginInProgress,
  secureStorage,
  persistence,
  unusableHomeserver,
  internal,
}

/// Err nunca afirma sucesso local; o cliente permanece reservado para nova tentativa.
enum LogoutError {
  notAuthenticated,
  logoutInProgress,
  authenticationOperationInProgress,
  secureStorage,
  localCleanup,
  internal,
}

/// Sucesso local confirmado; avisos não incluem detalhes remotos nem segredos.
class LogoutResult {
  final RemoteLogoutStatus remoteStatus;
  final bool storeCleanupPending;

  const LogoutResult({
    required this.remoteStatus,
    required this.storeCleanupPending,
  });

  @override
  int get hashCode => remoteStatus.hashCode ^ storeCleanupPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogoutResult &&
          runtimeType == other.runtimeType &&
          remoteStatus == other.remoteStatus &&
          storeCleanupPending == other.storeCleanupPending;
}

enum MatrixStreamError {
  notAuthenticated,
  subscriberLimit,
  subscriptionClosed,
  internal,
}

enum MatrixSyncStatus {
  connecting,
  connected,
  reconnecting,
  authenticationRequired,
}

/// subscription_id/sequence controlam entrega, nunca representam tokens Matrix.
class MatrixUpdate {
  final String subscriptionId;
  final int sequence;
  final MatrixUpdateKind kind;
  final String? conversationId;
  final MessageSummary? message;
  final MatrixSyncStatus status;

  const MatrixUpdate({
    required this.subscriptionId,
    required this.sequence,
    required this.kind,
    this.conversationId,
    this.message,
    required this.status,
  });

  @override
  int get hashCode =>
      subscriptionId.hashCode ^
      sequence.hashCode ^
      kind.hashCode ^
      conversationId.hashCode ^
      message.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixUpdate &&
          runtimeType == other.runtimeType &&
          subscriptionId == other.subscriptionId &&
          sequence == other.sequence &&
          kind == other.kind &&
          conversationId == other.conversationId &&
          message == other.message &&
          status == other.status;
}

/// Apenas projeções da aplicação; nenhum evento ou token Matrix atravessa FRB.
enum MatrixUpdateKind { message, conversationsChanged, resyncRequired, status }

/// Categorias fixas sem conteúdo remoto ou detalhes internos.
enum MessageHistoryError {
  notAuthenticated,
  invalidConversationId,
  conversationNotFound,
  conversationNotJoined,
  encryptionUnsupported,
  network,
  tls,
  rateLimited,
  history,
  internal,
}

/// Projeção textual; eventos, JSON e segredos do SDK permanecem em Rust.
class MessageSummary {
  final String id;
  final String senderId;
  final String body;
  final PlatformInt64 timestampMs;
  final bool isOwn;

  const MessageSummary({
    required this.id,
    required this.senderId,
    required this.body,
    required this.timestampMs,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      body.hashCode ^
      timestampMs.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          body == other.body &&
          timestampMs == other.timestampMs &&
          isOwn == other.isOwn;
}

/// Categorias estáveis; detalhes do SDK e do servidor não atravessam a ponte.
enum ProbeError {
  invalidServerAddress,
  network,
  tls,
  unusableHomeserver,
  internal,
}

/// A sessão já revogada também satisfaz o encerramento remoto.
enum RemoteLogoutStatus {
  confirmed,
  alreadyInvalid,
  network,
  tls,
  rateLimited,
  server,
  internal,
}

/// Falhas fixas; uma falha de transporte pode deixar a aceitação remota incerta.
enum SendMessageError {
  notAuthenticated,
  invalidConversationId,
  conversationNotFound,
  conversationNotJoined,
  encryptionUnsupported,
  emptyMessage,
  messageTooLong,
  sendInProgress,
  network,
  tls,
  rateLimited,
  send,
  internal,
}

/// Confirmação do servidor; o envio não fornece origin_server_ts nem evento completo.
class SendMessageResult {
  final String eventId;

  const SendMessageResult({required this.eventId});

  @override
  int get hashCode => eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendMessageResult &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId;
}

/// Informações da aplicação obtidas somente após uma resposta Matrix válida.
class ServerInfo {
  final String serverAddress;
  final bool supportsPasswordLogin;

  const ServerInfo({
    required this.serverAddress,
    required this.supportsPasswordLogin,
  });

  @override
  int get hashCode => serverAddress.hashCode ^ supportsPasswordLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          serverAddress == other.serverAddress &&
          supportsPasswordLogin == other.supportsPasswordLogin;
}

/// Falhas locais e remotas classificadas sem conteúdo de arquivos ou do cofre.
enum SessionError {
  operationInProgress,
  network,
  tls,
  invalidSession,
  corruptedSession,
  secureStorage,
  persistence,
  internal,
}

/// Estado seguro: nenhum token, DTO do SDK ou chave pode atravessar FRB.
class SessionState {
  final AccountSummary? account;

  const SessionState({this.account});

  @override
  int get hashCode => account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionState &&
          runtimeType == other.runtimeType &&
          account == other.account;
}
