// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Consulta os métodos de acesso sem autenticar ou reter um cliente global.
Future<ServerInfo> probeServer({required String address}) =>
    RustLib.instance.api.crateApiSimpleProbeServer(address: address);

/// A senha atravessa a ponte somente nesta direção e não integra o estado da conta.
Future<AccountSummary> login({
  required String homeserverAddress,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSimpleLogin(
  homeserverAddress: homeserverAddress,
  username: username,
  password: password,
);

/// Sincroniza uma única vez e retorna somente salas ingressadas que não são espaços.
Future<List<ConversationSummary>> listConversations() =>
    RustLib.instance.api.crateApiSimpleListConversations();

/// Projeção pública da conta; a sessão e seus segredos permanecem no SDK em Rust.
class AccountSummary {
  final String userId;
  final String deviceId;
  final String homeserverAddress;

  const AccountSummary({
    required this.userId,
    required this.deviceId,
    required this.homeserverAddress,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ deviceId.hashCode ^ homeserverAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountSummary &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserverAddress == other.homeserverAddress;
}

/// Categorias seguras, sem respostas do servidor nem segredos da sessão.
enum ConversationError {
  notAuthenticated,
  network,
  tls,
  rateLimited,
  synchronization,
  internal,
}

/// Resumo de apresentação; o identificador é opaco para Flutter, sem tipos Matrix.
class ConversationSummary {
  final String id;
  final String displayName;

  const ConversationSummary({required this.id, required this.displayName});

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName;
}

/// Falhas estáveis sem mensagens, respostas ou objetos de autenticação do SDK.
enum LoginError {
  invalidServerAddress,
  invalidInput,
  passwordLoginUnsupported,
  invalidCredentials,
  network,
  tls,
  rateLimited,
  alreadyAuthenticated,
  loginInProgress,
  unusableHomeserver,
  internal,
}

/// Categorias estáveis; detalhes do SDK e do servidor não atravessam a ponte.
enum ProbeError {
  invalidServerAddress,
  network,
  tls,
  unusableHomeserver,
  internal,
}

/// Informações da aplicação obtidas somente após uma resposta Matrix válida.
class ServerInfo {
  final String serverAddress;
  final bool supportsPasswordLogin;

  const ServerInfo({
    required this.serverAddress,
    required this.supportsPasswordLogin,
  });

  @override
  int get hashCode => serverAddress.hashCode ^ supportsPasswordLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          serverAddress == other.serverAddress &&
          supportsPasswordLogin == other.supportsPasswordLogin;
}
